<!-- Modal Status -->
<div class='modal fade' id='<?php echo $this->name; ?>-stat' tabindex='-1'
	role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
	<div class='modal-dialog'>
		<div class='modal-content'>
			<form method='post' enctype='multipart/form-data'>
				<div class='modal-header'>
					<button type='button' class='close' data-dismiss='modal'
						aria-hidden='true'>&times;</button>
					<h4 class='modal-title'>Load History Status</h4>
				</div>
				<div class='modal-body'>

					<!--  Begin history table -->
					<div id="BatchHistoryTable-stat">
					
					</div>
				</div>
				<div class='modal-footer'>
					<button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
					
				</div>
			</form>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->


<script>

$( document ).ready(function() {$('#<?php echo $this->name; ?>-stat').modal();});


var timer;

function doPoll(){
    $.post('ajax/test.html', function(data) {
    	$( "#BatchHistoryTable-stat" ).load( window.location.pathname + "?batchtablehistory=true" );
    	timer = setTimeout(doPoll,5000);
    });
}

// start polling the batch history when the modal is shown
$('#<?php echo $this->name; ?>-stat').on('show.bs.modal', function () {
	doPoll();
})
	
// stop polling the batch history when the modal is hidden
$('#<?php echo $this->name; ?>-stat').on('hidden.bs.modal', function () {
	clearTimeout(timer);
	window.location = document.URL;
    return false;
})

</script>
