<!-- Modal Upload -->
<div class='modal fade' id='<?php echo $this->name; ?>' tabindex='-1'
	role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
	<div class='modal-dialog'>
		<div class='modal-content'>
			<script>
	        function <?php echo $this->name; ?>_on_submit() {
	          if (typeof document.getElementById('upload').files != 'undefined') {
			    if (document.getElementById('upload').files[0].size > <?php echo $this->MAX_FILE_SIZE; ?>) {
			      alert('File size is too large.');
			      return false;
			    }
			  }
	          $('#<?php echo $this->name; ?>').modal('hide');
	          $('#pleaseWaitDialog').modal();
			  return true;
			}
        </script>
			<form method='post' enctype='multipart/form-data'
				onsubmit='return <?php echo $this->name; ?>_on_submit()'>
				<div class='modal-header'>
					<button type='button' class='close' data-dismiss='modal'
						aria-hidden='true'>&times;</button>
					<h4 class='modal-title'><?php echo $this->Title; ?></h4>
				</div>
				<div class='modal-body'>
					<!-- Name of input element determines name in the array -->
					<input id='upload' class='btn btn-default' type='file'
						name='<?php echo $this->name; ?>'>
					<p class='help-block'><?php echo $this->Help; ?></p>
				</div>
				<div class='modal-footer'>
					<button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
					<button type='submit' class='btn btn-primary'>Upload File</button>
				</div>
			</form>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<!-- End Modal Upload -->
<div class="modal" id="pleaseWaitDialog" role='dialog' aria-labelledby='myModalLabel2' aria-hidden='true'>
	<div class='modal-dialog'>
		<div class='modal-content'>
			<div class="modal-header">
				<h1>Processing...</h1>
			</div>
			<div class="modal-body">Depending on the size of the data this may take some time. <br /><br />Please Wait.</div>
		</div>
	</div>
</div>